# netlify.toml

[build]
  publish = "public"  # Le dice a Netlify que la carpeta "public" es tu frontend
  command = "echo 'Deploying frontend and functions...'" # Un comando simple de construcci칩n

[functions]
  directory = "functions" # Le dice a Netlify d칩nde est치n tus funciones sin servidor
  node_bundler = "esbuild" # Un bundler r치pido para Node.js